### ISSUE TITLE
Provide docker example for zmq

### ISSUE THREAD

**Issue by arekkas** [Originate/exosphere-website#4]
Brew isn't available on linux and windows but Docker is. Also, I don't want to install zmq globally only for trying out exo. It would be great to provide a docker example in [install.md](https://github.com/Originate/exosphere-website/blob/master/install.md)

**Comment by kevgo** [comment]
How exactly do you see ZMQ running in Docker? The reason for the ZMQ dependency of the SDK is that the [zmq NPM module](https://github.com/JustinTulloss/zeromq.node) npm module needs the ZMQ header files to compile the native bindings. 

I have added more installation instructions for other platforms.

Btw one of our next milestones is to lean fully on Docker for all external dependencies (databases, libraries, etc). So that when one works on an Exosphere app that needs MongoDB, Memcache, or ElasticSearch, it downloads and spins up those dependencies via Docker on your machine.

**Comment by arekkas** [comment]
> How exactly do you see ZMQ running in Docker?

Is ZMQ embedded? If yes, I didn't know that! You could however ship the stuff that embeds ZMQ via docker.

**Comment by kevgo** [comment]
Yes, ZMQ is just a socket on steroids, adding better buffering, multi-point connections, etc. But ultimately it is just a C socket library running as part of your code. It needs the headers to compile the library on the target machine. Why the npm module doesn't include the headers itself I don't know.

**Comment by arekkas** [comment]
superseded by https://github.com/Originate/exosphere-sdk/issues/123
